spring:
  application:
    name: msavaliadorcredito

server:
  port: 0

eureka:
  client:
    register-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
